services:

  adminer:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports: 
    - 8081:80
    networks:
    - backend
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD

  database:
    image: postgres:latest 
    ports:
    - 5432:5432 
    hostname: $PSQL_HOST
    environment:
      - POSTGRES_USER=$PSQL_USER
      - POSTGRES_PASSWORD=$PSQL_PASSWORD
      - POSTGRES_DB=expenses
    container_name: psql
    networks:
    - backend 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - expense-data-prd:/var/lib/postgresql/data
  
  api: 
    image: berliozintegrator/expenses-backend
    build: 
      context: ./backend
    ports: 
    - 5000:5000
    networks:
    - backend 
    - frontend 
    environment:
      - PSQL_USER=$PSQL_USER
      - PSQL_PASSWORD=$PSQL_PASSWORD 
      - PSQL_DB_NAME=$PSQL_DB_NAME
      - PSQL_HOST=$PSQL_HOST
    container_name: api 
    hostname: backend
    depends_on:
      - database

  frontend: 
    image: berliozintegrator/expenses-frontend
    build: 
      context: ./frontend
    volumes: 
    - ./frontend:/app 
    working_dir: /app 
    ports: 
    - 80:80
    networks:
      - frontend 
    depends_on:
      - api

  grafana:
    image: grafana/grafana
    hostname: grafana
    ports: 
    - 3000:3000
    networks: 
      - backend
      - frontend
    depends_on:
      - api

volumes:
  expense-data-prd:

networks:
  frontend: 
  backend:
